# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: superterran dot com
email: superterran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just some guy with a laptop and not enough time on my hands. Here's hoping
  that with a little love and care this sapling mess of html and markdown will
  keep growing. I'll try to keep my contributions short and useful!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://superterran.com" # the base hostname & protocol for your site

twitter_username: superterran
github_username:  superterran
facebook_username: doug.hatcher
linkedin_username: doughatcher
codepen_username: superterran

# Build settings
markdown: redcarpet
